# Generated by Django 4.2.23 on 2026-01-12 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriesm',
            name='slug',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
